name: Deploy Astro site to GitHub Pages

on:
  push:
    branches:
      - main # Trigger the workflow when a push to the main branch occurs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.3.0" # Use Node.js version 20.3.0

      - name: Install dependencies
        run: npm install

      - name: Build the Astro site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Adjust if your output directory is different
